services:
  fortezy_automotive_app:
    build:
      context: . # Use the current directory for the Dockerfile
      dockerfile: Docker/Dockerfile.dev # Path to the Dockerfile
    container_name: fortezy_automotive_app
    volumes:
      - .:/var/www/html # Mount the current directory (Laravel app) to the container
    networks:
      - postgresql-network
      - fortezy-automotive-admin-network

  fortezy_automotive_nginx:
    image: nginx:latest # Use the latest Nginx image
    container_name: fortezy_automotive_nginx
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - .:/var/www/html # Mount the current directory (Laravel app) to the container
      - ./Docker/config/nginx.conf:/etc/nginx/nginx.conf  # Use a custom Nginx config file
    depends_on:
      - fortezy_automotive_app
    networks:
      - fortezy-automotive-admin-network

  fortezy_automotive_nodejs:
    image: node:20 # Use Node.js 20 as the base image
    container_name: fortezy_automotive_nodejs
    working_dir: /var/www/html # Set working directory to your Laravel app directory
    command: sh -c "npm install && npm run dev && tail -f /dev/null"
    volumes:
      - .:/var/www/html # Mount the current directory (Laravel app) to the container
    depends_on:
      - fortezy_automotive_app
    networks:
      - fortezy-automotive-admin-network

networks:
  postgresql-network:
    external: true  # Use the existing postgresql-network
  fortezy-automotive-admin-network:
    external: true  # Use the existing fortezy-automotive-admin-network
